name: Build Java-Aks project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v5
      
      # - name: Set up JDK 17
      #   uses: actions/setup-java@v5
      #   with:
      #     distribution: temurin
      #     java-version: 17

      - name: Checkout and setup java 17
        uses: ./.github/workflows/init.yml
      
      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: aks-java-demo-jar
          path: target/*.jar
